### ISSUE TITLE
unixODBC is no longer conflicting with libiodbc

### ISSUE THREAD

**Issue by willysr** [aclemons/slackrepo-default-hints#1]
Since this commit: https://git.slackbuilds.org/slackbuilds/commit/?id=a1f4113cddde8494231c9553c145382876dff680
unixODBC no longer overwrite Slackware's libiodbc, so the hint files should be updated

**Comment by aclemons** [comment]
I'll update it and then check the latest saga-gis submission.

**Comment by aclemons** [comment]
Done in 6da2733dab46c3eb6086b5fc47c8c19761416121
